### ISSUE TITLE
[Feature]: How to support RDCMan.exe

### ISSUE THREAD

**Issue by Anoyou** [Whisky-App/Whisky#329]
### Is your feature request related to a problem?

Although I know most people use it to run Windows games, I just want to run some small productivity software.I have already configured the operating environment, but I can't get it to work, not even with a portable app.

### Describe the solution you'd like

I'm just a normal user, I don't know why it doesn't work, and Whiskey doesn't give any hint.Although the possibility is very small and the need is very, very small, I would like to support this class,thanks.

### Anything else?

Remote Desktop Connection Manager v2.93(RDCMan.exe) download link：https://learn.microsoft.com/en-us/sysinternals/downloads/rdcman

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
See, the issue isn't that you can't run it (You can), the issue is that it would be quite useless (It's merely a GUI to run `mstsc.exe` which is the actual client preinstalled on Windows, and Wine doesn't have it). I highly suggest looking into alternatives which are also readily available on Mac.

If you are so inclined, install [Wine Mono](https://dl.winehq.org/wine/wine-mono/) and then the app will start
