### ISSUE TITLE
[Feature]: Please remove the confusing and unnecessary Show/Hide Sidebar button

### ISSUE THREAD

**Issue by rxhfcy** [Whisky-App/Whisky#433]
### Is your feature request related to a problem?

The Show/Hide Sidebar button is confusing and unnecessary. I genuinely can't imagine why someone would want to use it (intentionally).

### Describe the solution you'd like

Please remove the Show/Hide Sidebar button, which is an unnecessary annoyance / footgun (especially for beginners) with no compelling use cases. The Whisky UI is delightfully simple and clean otherwise, but this button genuinely puzzles me.

Genuinely curious: who would intentionally want to hide the Sidebar? Why?
If it was your decision, would you add a "Show/hide Sidebar" button to macOS Finder too? What about CrossOver?

### Anything else?

Nope. Thanks for considering this.

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
That button is standard on macOS.

**Comment by arkon** [comment]
I hid the sidebar and also do so in apps like Notes.

**Comment by arkon** [comment]
I'm just providing a data point since I happened to see this while looking for another issue.

You can always consult the official UX guidelines: https://developer.apple.com/design/human-interface-guidelines/sidebars

I don't really think it's a foot gun for any user that's vaguely familiar with modern apps on Apple platforms so I'd at least like to voice that I like having the option.

It's up to the dev to decide though, I'm not here to argue about established UX practices.
