### ISSUE TITLE
[Bug]: Cannot switch Enhanced Sync type from MSync to anything else

### ISSUE THREAD

**Issue by R3D4CTED** [Whisky-App/Whisky#598]
### Description

I updated Whisky today, updated GPTK, and then MSync was selected. When I tried to switch to ESync or turn it off, steam doesn't load anymore, and the Windows Build Version in the Bottle Configuration just shows up as "0". Attempting to switch windows versions also doesn't work and hangs the application.

### Steps to reproduce

Go to bottle configuration, change the Enhanced Sync type from MSync to Esync or turn it off.

### Expected behaviour

Enhanced Sync should either disable or ESync should be selected, without making the windows version 0.

### Logs

```bash
Whisky Version: 2.1.3
Date: 2023-11-04T15:33:13Z
macOS Version: 14.0.0

Bottle Name: Testing
Bottle URL: /Volumes/T7/Bottle Cellar/Test/7B66DA42-B7B5-45B9-BA2A-B5F3DCA79EA3

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: esync

Metal HUD: false
Metal Trace: false

DXVK: true
DXVK Async: true
DXVK HUD: off

Arguments: start /unix /Volumes/T7/Bottle Cellar/Test/7B66DA42-B7B5-45B9-BA2A-B5F3DCA79EA3/drive_c/Program Files (x86)/Steam/steam.exe -noverifyfiles 

Environment:
{
    WINEDLLOVERRIDES = "dxgi,d3d9,d3d10core,d3d11=b";
}

Launched Wine (19328)
Process exited with code 8
```

### What version of Whisky are you using?

2.1.3

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by cuba** [comment]
I'm not seeing your issue. However
1. Make sure you have the latest version of the application, there was a problem with setting ESync which has been fixed
2. Setting enhanced sync shouldn't affect your windows version, so something else must be going on here with your wine setup

One thing you can try is 
1. Open Registry Editor and search for "CurrentBuild". (Or manually navigate to HKEY_LOCAL_MACHINE -> Software -> Microsoft -> Windows NT -> Current Version)
2. Make sure "CurrentBuild" and "CurrentBuildNumber" is set to the appropriate value. Perhaps you want 19042

You can also try recreating a bottle and seeing if the issue is reproducible in a new bottle. Perhaps something is wrong with your bottle.

<img width="755" alt="Screenshot 2023-11-04 at 11 34 52 AM" src="https://github.com/Whisky-App/Whisky/assets/909331/c52abf06-5098-40bb-93b8-3f3131ec2462">

**Comment by R3D4CTED** [comment]
<img width="497" alt="image" src="https://github.com/Whisky-App/Whisky/assets/28143681/2b8d61e3-2984-448a-ae7c-bd75ccf50fa4">
weirdly enough, my build number always sets itself to this version when I select Windows 10. So another thing I forgot to mention is that the other bottle was created with an older version of Whisky, and is present on an external drive. I tried reproducing on a new bottle, but that seems fine.
