### ISSUE TITLE
How to type Chinese in Whisky?

### ISSUE THREAD

**Issue by ewayuan** [Whisky-App/Whisky#840]
### Description

How to type Chinese in Whisky?

### Steps to reproduce

N/A

### Expected behaviour

type Chinese pinyin

### Logs

```bash
N/A
```

### What version of Whisky are you using?

2.2.3

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by gywghhb** [comment]
Yes, you can simply use the Chinese input method on your Mac. I'm guessing your problem is more of the issue of Chinese characters not showing as they're not bundled by default. You should download cjkfonts and corefonts then try again. Here's a guided tutorial I've found (in Chinese): [](https://blog.zhheo.com/p/da8637c7.html)

**Comment by IsaacMarovitz** [comment]
<img width="1077" alt="Screenshot 2024-03-31 at 22 59 23" src="https://github.com/Whisky-App/Whisky/assets/42140194/1f630f93-6c8c-4578-b91a-5561150657b5">

Install `allfonts` or `cjkfonts` into your prefix with Winetricks.
