### ISSUE TITLE
[Bug]: Cannot run Steam

### ISSUE THREAD

**Issue by jaypeetee** [Whisky-App/Whisky#957]
### Description

I am unable to run and install Steam

### Steps to reproduce

1. Install Whiskey and dependencies
2. Create a new bottle named "Steam" running Windows 10
3. Click the "Run" button, browse to the downloaded file "SteamSetup.exe", and choose "Open"
4. Nothing happens

### Expected behaviour

Steam should launch successfully

### Logs

```bash
Whisky Version: 2.3.2
Date: 2024-04-26T18:23:28Z
macOS Version: 14.4.1

Bottle Name: Steam
Bottle URL: /Users/joe/Library/Containers/com.isaacmarovitz.Whisky/Bottles/59D5CDF0-3996-45AE-BD3E-F31BE949BB04

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: start /unix /Users/joe/Downloads/SteamSetup.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    "GST_DEBUG" = 1;
    WINEDEBUG = "fixme-all";
    WINEESYNC = 1;
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/joe/Library/Containers/com.isaacmarovitz.Whisky/Bottles/59D5CDF0-3996-45AE-BD3E-F31BE949BB04";
}

msync: bootstrapped mach port on wine-237d7e-msync.
msync: up and running.
```

### What version of Whisky are you using?

2.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
I cannot recreate the issue.

**Comment by DANN9687** [comment]
I've had this same issue

**Comment by DANN9687** [comment]
I'm running M2 Max, Sonoma 14.4.1. 
I did realise that it didn't ask me to download GPTK if that makes a difference ??

**Comment by lzy728** [comment]
me too

**Comment by lucaspaolo** [comment]
I tried several Whiskey versions to run steam in a bottle and it doesn't worked on my side too

**Comment by mathewhillier** [comment]
i also have the same problem with Steam windows installer not working in winesky. 

I have got the steam setup window to appear (had to right-click it on the finder and then choose 'open' because  mac was preventing it to open). however - the window is largely devoid of content. it only just shows two horiz white lines. looking at youtube i work out where on the window to click 'next' on the install wizard. But then it shows a 'program error' window with blank area where the error message should be - so i am none the wiser.  Screen image of the blank steam installer window is attached.
<img width="661" alt="winsky_steam_win_setup_blank_window" src="https://github.com/Whisky-App/Whisky/assets/976376/22d791e3-14d5-4a10-ac70-933a8c2ea898">

The inbuilt windows 'notepad.exe' in winsky works fine.

Any pointers as to what may be wrong there? 

Macos 14, latest winsky and steam installers as of today, Mac Air, M1, 16GB ram. 

i have tried combos of turning on / off msync, metal hud etc but it doesn't help.

log is below:
Whisky Version: 2.3.2
Date: 2024-04-28T14:22:49Z
macOS Version: 14.3.1

Bottle Name: steam_win
Bottle URL: /Users/joe/Library/Containers/com.isaacmarovitz.Whisky/Bottles/C6C35CAF-A390-468C-B875-D38306FC9EB6

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: true
Metal Trace: false

DXVK: true
DXVK Async: true
DXVK HUD: off

Arguments: start /unix /Users/joe/Library/Containers/com.isaacmarovitz.Whisky/Bottles/C6C35CAF-A390-468C-B875-D38306FC9EB6/drive_c/SteamSetup.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    "GST_DEBUG" = 1;
    "MTL_HUD_ENABLED" = 1;
    WINEDEBUG = "fixme-all";
    WINEDLLOVERRIDES = "dxgi,d3d9,d3d10core,d3d11=n,b";
    WINEESYNC = 1;
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/joe/Library/Containers/com.isaacmarovitz.Whisky/Bottles/C6C35CAF-A390-468C-B875-D38306FC9EB6";
}

msync: bootstrapped mach port on wine-3ae5189-msync.
msync: up and running.
﻿

**Comment by meerkatriptide** [comment]
Same issue here, M1 Pro, Sonoma 14.4.1

**Comment by jaypeetee** [comment]
Min is M3, 16Gb, Sonoma 14.4.1

**Comment by IsaacMarovitz** [comment]
If you're having problems with Steam, it is an issue of user error, not an issue with the app. Please go to the Discord for in-depth support: https://discord.gg/CsqAfs9CnM
